spring.application.name=apirestmuralvagas

# Coordenadas e Credenciais do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_muralvagas
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# O "update" diz ao Spring para ler as suas classes @Entity e criar/atualizar as tabelas automaticamente no banco.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está a executar (ótimo para ver o que está a acontecer)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Caminho para aceder ao Swagger no navegador
#springdoc.swagger-ui.path=/swagger-ui.html
#
# Caminho da documentação em formato JSON
#springdoc.api-docs.path=/api-docs